#ifndef CUB3D_ERRORS_H
# define CUB3D_ERRORS_H

# define ERROR_CODE int

# define ERROR_WRONG_ARG_AMT 1
# define ERROR_WRONG_SECOND_ARG 2
# define ERROR_WRONG_PAR_REZ 3
# define ERROR_TEX_NO_NOT_FOUND 4
# define ERROR_TEX_SO_NOT_FOUND 5
# define ERROR_TEX_WE_NOT_FOUND 5
# define ERROR_TEX_EA_NOT_FOUND 6
# define ERROR_TEX_SPR_NOT_FOUND 7
# define ERROR_WRONG_PAR_FLOOR 8
# define ERROR_WRONG_PAR_CEIL 9


#endif
