#ifndef CUB3D_ERRORS_H
# define CUB3D_ERRORS_H

# define ERROR_CODE int

# define ERROR_WRONG_ARG_AMT 1
# define ERROR_WRONG_SECOND_ARG 2
# define ERROR_WRONG_PAR_REZ 3
# define ERROR_TEX_NO_NOT_FOUND 4
# define ERROR_TEX_SO_NOT_FOUND 5
# define ERROR_TEX_WE_NOT_FOUND 5
# define ERROR_TEX_EA_NOT_FOUND 6
# define ERROR_TEX_SPR_NOT_FOUND 7
# define ERROR_WRONG_PAR_FLOOR 8
# define ERROR_WRONG_PAR_CEIL 9
# define ERROR_NOT_A_PAR 10
# define ERROR_NOT_ALL_INFO 11
# define ERROR_CAN_NOT_ALLOCATE_MEMORY 12

# define ERROR_TWO_PLAYERS_ON_MAP 13
# define ERROR_MAP_ERROR 14
# define ERROR_CANT_GET_MAP_LINE 15
# define ERROR_NO_PLAYER_ON_MAP 16
# define ERROR_MAP_NOT_CLOSED 17

# define ERROR_MLX_DO_NOT_START 18

# define ERROR_WRONG_FIRST_ARG 19
# define ERROR_CANT_OPEN_CUB_FILE 20

#define ERROR_CANT_CREATE_SCREEN_FILE 21

#endif
